### ISSUE TITLE
Github action for unit tests

### ISSUE THREAD

**Issue by jepusto** [jepusto/metaselection#3]
Configure Github action to run unit tests.

**Comment by jepusto** [comment]
And also code coverage if feasible.

**Comment by meghapsimatrix** [comment]
This is the R-CMD-check and test-coverage right?

**Comment by jepusto** [comment]
Yup.

**Comment by jepusto** [comment]
Looks like there's some issue with the codecov configuration?

**Comment by jepusto** [comment]
Closed after adding CODECOV_TOKEN to repository secrets.
